keywords: Hexo, theme-bmw

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件
rss: 

# 自定义样式文件
custom_style: /custom/style.css

# 自定义脚本文件
# loc: 脚本文件位置
# load: 加载方式
custom_script: 
  - 
    src: /custom/script.js
    load: async

# 是否渲染 文章目录
toc: true

# 是否支持 数学公式
mathjax: true

# 是否开启 音乐组件
player: true

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: qzone, qq, weibo, wechat, douban, google, facebook, twitter
  disabled: 

# 是否开启 打赏功能
reward: 
  enable: true
  meta: 知识 & 情怀 | 二者兼得 
  button_meta: 投食
  qrcodes:
    -
      src: /images/wechat.png
      meta: "微信扫一扫, 向我投食"
    -
      src: /images/alipay.png
      meta: "支付宝扫一扫, 向我投食"

# 是否开启版权声明
copyright: 
  enable: true
  author: 董沅鑫
  license: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议。转载请注明出处！'

# 页脚信息 
footer: 
  start: "2018-02-10"
  more: '<a href="https://www.google.com/analytics/" target="_blank">Google Analytics</a> 提供网站统计服务. 
    <a href="https://sg.godaddy.com/"  target="_blank">GoDaddy</a> 提供域名注册服务. 
    <br>
    <a href="https://www.trustasia.com/" target="_blank">TrustAsia</a> 签发SSL证书. 
    <a href="http://www.miibeian.gov.cn/state/outPortal/loginPortal.action" target="_blank">粤ICP备18028400号</a> .
  '

# 开启 评论 & 统计 插件 : https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: true # 是否开启评论系统
  timer: true # 是否开启文章统计

# 导航栏头部名称
nav_name: GODBMW.com 
# 导航栏选项
# blank: 是否在新页面打开，默认 false
# children：开启二级导航栏
nav: 
  - 
    name: 主页
    path: /
  -
    name: 归档
    path: /archives/
  -
    name: 分类
    path: /categories/
  -
    name: 标签
    path: /tags/
  -
    name: 友链
    path: /friends/
  - 
    name: 关于
    path: /about/
  -
    name: 抓到我
    children:
      -
        name: Github
        path: "https://github.com/dongyuanxin"
        blank: true
      -
        name: "SegmentFault"
        path: "https://segmentfault.com/u/godbmw"
        blank: true

# 友链详细信息
friends:
  -
    nickname: GodBMW
    avatar: /images/friends/godbmw.jpeg
    site: https://godbmw.com
    meta: 啦啦啦♪(^∇^*)
    show: true
  -
    nickname: 菜鸟博客
    avatar: /images/friends/birdteam.png
    site: https://birdteam.net/
    meta: Linux运维工程师相关技术教程
    show: true
  -
    nickname: 青南
    avatar: /images/friends/avatar.png
    site: https://www.kingname.info
    meta: 给时光以生命
    show: true
  -
    nickname: ChungZH
    avatar: /images/friends/chungzh.jpg
    site: https://chungzh.cn
    meta: 向着梦想加油
    show: true